language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: V/QW3PUVJ5WN2IWAGa2Lmk7L+2/UJx69hZzkN7g7YokPt5KrDstybuY8NFtT3E5RX3eUCptjYVFKnsKQMmNQagA8j5hOQgvuzuaAFhSs0LRBEbp+U4ON2p+4MNZDUtBhiVCJ4KjdW68UAHwpAfwAs2kbFb81N1C4dk7X1oug2qAmbT8Tg45pb9dvbsUVEhaN07vhJik/pFAmH2Y2V9Aotw/Vwhmb2vNWrzec6oudeMA17/GtqUN0JFSmq8QP4ZzYJ+4pMXaVSh4hEzDYz/mk5GDC2HnuL/dgn2UiclWg9AOXFfDXCQ/i38aGYlX15ZL31tBYmupsBvDBxzCyQrg4aZhVdw5CO1xI/lLs/zu1RUwj+FrmrOtiktHh48Qzlg+vAwgYtxXwpu7eBwmno7kgYwHO1b+v5N4HNCl0Dti16d/i63RFmHcy4IuWexQvVFTuQ1NyhWJM4R6tzN5Xleti9m9nr50FAQobAZlnfizPTs69re0EjlP5fKGx72zZYChDxHrJGb9+79p7sRK7rE5dYD6Ddazoymztbd/NjR0RS0JOZu+EdIS2kkbIUalNamF5V+2S5ga6W+W+H01kE18r8wSVDyOI7IzZltpvwo8Z8KDvPc653n0nMWjeGlT0bAgwfyeIRSoolbQt0bGYa1u8xbO2lL9plu7TsWDSWqJqEso=
  - secure: QBaU9NLBore7WQybU70yozaX2B/BBmdKpCA07KpBQLJ3GbAxui/SfqR5NKd/5nMbFrFK4/nB+NHwOwJreMKk0zfzzJ8M1OX5FGwm6ZDuqFUisoVQv6IAndWJNbXg4fiXgX803M2WwMyA1zkDnQEzSXnw8yrwP/nbFqPStd1DFGJvMKHwXShQKNCvLHhYBITkfwQ0QyYsKpHA2xjYvfJbyLVbv4tXe9asjdnxB/Ma4HAAQWHSKu0zBrIxVHUTZr3zJvWGpHqBM2Fjk7PO9XH9ZPoXygnwO9f1Yyy2GqAvhfG5fB6dpEG9lrwSBQ2LHq0O4QhLdxo5fh/7M+7Qxb0jGUe1Y2X6T0XSt3SJ2k0JJY7oP2arXxS6ei0rmJqtlK1pmNqoHlNo1AFoohfiM/ZKrXUVf/mQMy1AnFK1TVjAphRhxqX7NDj8Gb5JQaxYWYMygWolHQSf2+SNUdNVYvm9tIE0AOBBLCI2m3dudpxeE7EnvqBMH57kqOVoxZ4WosZ3W1dBt4Xvr1MC4QyY7DRnsarcPq8rxlO4k20/34uGerjnQMVBaManKlrL/GHEM+85auFNzlu79U2yHl9O28prZXFDPsj+iBkrCKrJBClwmz0CfKhmTWbN3MPnOqOM1co0VCjBniimJlhEwdwJXPf8ntorgU0a1ZkYxoR/YQC3KVk=
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: L6zmyiUkTyjMu53nmJ1Zl4teqdhZOLRWjBbdk4+zBIBuezTWDz+/KRijjg28oV5nFJpFm1M/5FRx9BbDYdZWSpwTS4/e9JZ3WBoF1EJ+Sq7ZbC0wI/Eid6ewJHT/G01qIs6NxYp2H1DSq2OAU2U69gV51bT4UhHEUGZW0RPvsJFKHS4qpriu3DLXghtg8hAHGG7LZHqxFRVhITk7jKGWfp733RygDCe0fzDirpG77Lhq9ZOnhwzngQYoGi+bVR5sPjr7SprHFF04eNEGimHse3hPE5e1zXpUFs/MXqz0evvBrQe4sgqht7noCz0UbvrYWMjJIh5Ki/TmfURsWNUBcr6vAnkeTZCXwJcMdtScHQ83C4gWATDXG3SWf11MD58MLTkpZ0f8pLMVaZCbbWzSXmtyp18DL74EP8EZBkd9RWVzF63ituRitBfaFjjxBz3zYBKpvd4Ql0+g4e5P4a5Km+Iqcf660L+8fVo2mka8NzdEKuvJ/57VfO5IfZ8EuSVDzdpPHbKjMgCh2r33v+Fz62L3w+Wt81A7AAv6wObOy53L6rLNGui1L0XEG6eaaJ/ZoFXMtlBmttkRoYuy9BnAJEVeaxfFCSUof0A7gMXy/mAVauBhBco5QZ/2cZiaZpP9Rk034s6wadXL1w3uKwPk3y50Ojg1GGuACyMhpxm0gQo=
  on:
    repo: plepers/nanogl-post
    branch: master
